robot_model:
  description:
    robot_description: "/anymal_description"

    ### upper body settings ########################################################
    bases:
      - idx: 0
        name: "PELVIS"
        shape: "CUBOID" # CUBOID, SPHERICAL
        size: {x: 1.0, y: 0.6, z: 0.6} # [m]
        link: "base"
        link_to_feet_center_offset: {x: 0.00, y: 0.00, z: -0.47, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad], transformation from geometric feet center to tf frame
    
    ### foot settings ##############################################################
    base_foot: &base_foot
      - shape: "SPHERICAL" # CUBOID, SPHERICAL
        size: {x: 0.06, y: 0.06, z: 0.06} # [m]
        # position (offset) of planner foot frame (center of sole) given in robot's "foot" link frame
        link_to_sole_offset: {x:  0.00, y:  0.00, z: -0.01, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]

    feet:
      - <<: *base_foot
        idx: 0
        name: "LF_LEG"
        link: "LF_FOOT"
        # the neutral stance describes the pose of each foot (center of sole) relative to the geometric feet center
        neutral_stance: {x:  0.365, y:  0.205, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 0.0, g: 1.0, b: 0.0, a: 0.6}

      - <<: *base_foot
        idx: 1
        name: "RF_LEG"
        link: "RF_FOOT"
        neutral_stance: {x:  0.365, y: -0.205, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 1.0, g: 0.0, b: 0.0, a: 0.6}

      - <<: *base_foot
        idx: 2
        name: "LH_LEG"
        link: "LH_FOOT"
        neutral_stance: {x: -0.365, y:  0.205, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 0.0, g: 0.6, b: 0.0, a: 0.6}

      - <<: *base_foot
        idx: 3
        name: "RH_LEG"
        link: "RH_FOOT"
        neutral_stance: {x: -0.365, y: -0.205, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 0.6, g: 0.0, b: 0.0, a: 0.6}

    ### leg settings ###############################################################
    legs:
      - idx: 0
        name: "LF_LEG"
        root_link: "base"
        tip_link: "LF_FOOT"
        joints: ["LF_HAA", "LF_HFE", "LF_KFE"]

      - idx: 1
        name: "RF_LEG"
        root_link: "base"
        tip_link: "RF_FOOT"
        joints: ["RF_HAA", "RF_HFE", "RF_KFE"]

      - idx: 2
        name: "LH_LEG"
        root_link: "base"
        tip_link: "LH_FOOT"
        joints: ["LH_HAA", "LH_HFE", "LH_KFE"]

      - idx: 3
        name: "RH_LEG"
        root_link: "base"
        tip_link: "RH_FOOT"
        joints: ["RH_HAA", "RH_HFE", "RH_KFE"]

    ### plugins ####################################################################
  plugins:
    kinematics:
      name: anymal_kinematics
      params:
        root_link: "base"
        leveled_base: False
        foot_type: "ball_foot"
        ignore_foot_orientation: True
    gait_generator:
      name: cyclic_gait_generator
      params:
        cycle: [0, 3, 1, 2]
        start: [0, 1, 2, 3]
        #cycle: [[0, 3], [1, 2]]
        #start: [[0, 3]]

